baseURL = "/"
languageCode = "ru-ru"
title = "Имперский Вестник"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = false
  defaultTheme = "auto"
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false
  hideFooter = false
  ShowRecentPosts = false


[[menu.main]]
identifier = "vypuski"
name = "Выпуски"
url = "/00-posts/"
weight = 1

[[menu.main]]
identifier = "svodki"
name = "Военные Сводки"
url = "/military-reports/"
weight = 3

[[menu.main]]
identifier = "projects"
name = "Проекты"
url = "/projects/"
weight = 2
