baseURL = "/"
languageCode = "ru-ru"
title = "Имперский Вестник"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = false
  defaultTheme = "auto"
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false
  hideFooter = false

[[menu.main]]
identifier = "vypuski"
name = "Выпуски"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "svodki"
name = "Военные Сводки"
url = "/military-reports/"
weight = 2
