baseURL = "/"
languageCode = "ru-ru"
title = "Имперский Вестник"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = false
  defaultTheme = "auto"
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false
  hideFooter = false

[params.homeInfoParams]
  Title = "Имперский Вестник 🦉"
  Content = """
Официальное и лицензионное СМИ Империи. Всё самое важное — в одном месте. И без ереси.

👉 [Выпуски газеты](/posts/)

👉 [Военные Сводки](/military-reports/)
"""


[[menu.main]]
identifier = "vypuski"
name = "Выпуски"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "svodki"
name = "Военные Сводки"
url = "/military-reports/"
weight = 2
